### PR TITLE
[JENKINS-50101] Add support for declarative pipeline

### PR DESCRIPTION
**Pull request by Dohbedoh**
@reviewbybees

### CODE REVIEW

**Comment by willwh** [comment]
Hi folks,

I'd really love to utilize this plugin from declarative pipelines. What is required to get this PR through?

@jglick your comment is not terribly clear :) most plugins seem to implement something really minimal in their `Jenkinsfile`s, and indeed, I don't see any changes to that in this PR?

**Comment by pascal-hofmann** [comment]
authorize project exists to limit permissions of jobs. A Jenkinsfile usually resides in the SCM. So with support for authorize project in Jenkinsfiles you would allow defining permissions from the code that's being built. This creates a security issue.

The real issue with authorize project is, that it does not work for multi branch jobs. See https://issues.jenkins-ci.org/browse/JENKINS-50559. For these there is currently no way to define a user for executing the build.

**Comment by jschewebbn** [comment]
I'm looking into using the Authorized Projects plugin and need support for declarative pipelines and multi-branch pipelins. It seems to me that allowing the developers to specify who to run the job as could be safely allowed if project based security were turned on and the user specified in the Jenkinsfile was a user with appropriate privileges in the project's security settings. I would think that would take care of the security hole. Am I missing something else?

**Comment by jglick** [comment]
I think this is something that needs to be specified at a different level, in whatever tool you use to generate `Item`s (https://plugins.jenkins.io/job-dsl/ is most popular though I would rather recommend something running outside the controller).

At any rate, a secure and usable design for integration with Pipeline-as-code would require concentrated thought, and currently this plugin does not even have a maintainer.

**Comment by jschewebbn** [comment]
From what I found so far this appears to be the only plugin that would allow one to restrict which jobs can run on which build executors. Are there others out there?

**Comment by jglick** [comment]
There is [`job-restrictions`](https://plugins.jenkins.io/job-restrictions/) and perhaps others. CloudBees CI also includes some features in this general area such as [trigger restrictions](https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-admin-guide/trigger-restrictions) and [controlled agents](https://docs.cloudbees.com/docs/cloudbees-ci/latest/traditional-secure-guide/folders-plus#_controlled_agents).

**Comment by jschewebbn** [comment]
Thank you for the suggestions. I'll take a look at `job-restrictions`.

**Pull request closed without merging**
