### PR TITLE
[JENKINS-32769] SpecificUsersAuthorizationStrategy cannot work for ACL.SYSTEM

### PR DESCRIPTION
**Pull request by stephenc**
Split from #13 

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by tfennelly** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by ikedam** [comment]
Though I'm not sure I actually need this change for security reasons, it's good idea to notice users that `SYSTEM` doesn't work as they expected.
I'll do the same for `ANONYMOUS`.

**Pull request merged**
