### PR TITLE
[WIP] Use recommended build configurations on ci.jenkins.io - DON'T MERGE

### PR DESCRIPTION
**Pull request by darxriggs**
The plugin is tested with multiple Jenkins and Java versions then.
For more details see https://github.com/jenkins-infra/pipeline-library.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@darxriggs one catch here is that the Pipeline changes will not be accepted unless you have WRITE permissions to the repo. So this change has no effective effect if submitted by you

**Comment by darxriggs** [comment]
Yes, I know that this has to be merged to the default branch before having any effect on other pull requests and even this one.

**Comment by darxriggs** [comment]
Ok. I checked locally with Java 8 & 11 and Jenkins 2.60.3 and 2.164.1.
There are marshalling errors (https://jenkins.io/redirect/class-filter/) that have to be fixed.

**Comment by ikedam** [comment]
> the Pipeline changes will not be accepted unless you have WRITE permissions to the repo

That’s so inconvenient as we can’t see the build will succeed after merging.
Is it resolved if I create and push a working branch merging this request?

**Comment by darxriggs** [comment]
Just for reference: You see which Jenkinsfile is used in a build's log - for example https://ci.jenkins.io/job/Plugins/job/authorize-project-plugin/job/PR-35/1/console

```
Connecting to https://api.github.com to check permissions of obtain list of darxriggs for jenkinsci/authorize-project-plugin
Loading trusted files from base branch master at 4b6110d3054b24b560882243b1ccdf6e4291454a rather than a67733292e7d40f66b6613f5a3fa8a34b741ccfd
Obtained Jenkinsfile from 4b6110d3054b24b560882243b1ccdf6e4291454a
[2019-08-15T12:23:57.670Z] ‘Jenkinsfile’ has been modified in an untrusted revision
```

**Comment by oleg-nenashev** [comment]
> That’s so inconvenient as we can’t see the build will succeed after merging.
Is it resolved if I create and push a working branch merging this request?

You would need to create a new pull request

**Comment by darxriggs** [comment]
I am already preparing other pull requests that have to be merged first, which contain changes to make the plugin / tests compatible with the latest Jenkins versions.

If all of these are merged I'll let you know.

I suggest that you then you create a new pull request performing this change here yourself or just reuse this single commit. And afterwards close this pull request unmerged.

**Comment by ikedam** [comment]
Created https://github.com/jenkinsci/authorize-project-plugin/tree/feature/35_RecommendedConfigurations
Jenkins is running on https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fauthorize-project-plugin/detail/feature%2F35_RecommendedConfigurations/1/pipeline

**Comment by darxriggs** [comment]
@ikedam I just rebased this branch on _master_ after all the merged pull requests to keep the history clean.

Could you therefore please reset the _feature/35_RecommendedConfigurations_ branch to this one?

I'll open a pull request against it that contains ALL the changes required for using `buildPlugin(configurations: buildPlugin.recommendedConfigurations())`.

**Comment by darxriggs** [comment]
After merging pull request #40, this one can be closed unmerged.

**Pull request merged**
