### PR TITLE
Require Jenkins 2.375.4 or newer

### PR DESCRIPTION
**Pull request by shoelzle**
update base jenkins version to 2.375.4

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by MarkEWaite — COMMENTED** [review]
Thanks for the pull request, but I'm not ready at this time to update the minimum required Jenkins version from 2.361.4 to 2.375.4.

Based on [plugin installation statistics](https://stats.jenkins.io/pluginversions/authorize-project.html), only 36% of installations of the plugin are installed on 2.375.1 or newer.  

The [update to 2.361.4 and Java 11](https://github.com/jenkinsci/authorize-project-plugin/releases/tag/authorize-project-1.5.1) was a strong incentive for users to upgrade to at least Jenkins 2.361.4 because that upgrade includes configuration as code.  However, it was only released last week.  I'd prefer to remain on Jenkins 2.361.4 as the minimum Jenkins version for a few months, at least until 2.361.4 is no longer one of the [recommended minimum Jenkins versions](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions).

**Comment by MarkEWaite** [comment]
@shoelzle was there a particular unexpressed reason that prompted this pull request?

**Comment by shoelzle** [comment]
@MarkEWaite, thanks for taking a look at my pull request.

There was no particular reason for me to create this pull request. I simply watched the ["Improve a plugin tutorial"](https://www.jenkins.io/blog/2022/09/21/improve-a-plugin-tutorial/) and increasing the Jenkins version was the first thing from the list where work seemed to be necassary.

I guess I didn't understand the implications of increasing the Jenkins version. Thanks for your explanation.

**Comment by MarkEWaite** [comment]
I've given some further thought to the change and I think it makes sense to update to Jenkins 2.375.4 as the minimum Jenkins version.  I expect the installation statistics for the plugin will be significantly different in the April 2023 report.  Thanks again for the contribution!

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
