### PR TITLE
Modernize plugin (upgrade parent pom & Java 8 compatibility)

### PR DESCRIPTION
**Pull request by darxriggs**
This is the base for more improvements.

### CODE REVIEW

**Comment by darxriggs** [comment]
I plan to have a look at [JCasC](https://jenkins.io/projects/jcasc/) compatibility which requires at least Jenkins 2.60.3.

**Comment by darxriggs** [comment]
Changes in this pull request are also required for branch [feature/35_RecommendedConfigurations](https://github.com/jenkinsci/authorize-project-plugin/tree/feature/35_RecommendedConfigurations).

**Comment by ikedam** [comment]
You can create a single pull request containing changes for upgrading to Jenkins 2.60 (A) and introducing JCaC (B) as they both are finally for B.
I believe we can distinguish which changes are for A and those for B. You can add comments on diffs if you worry about that.

**Comment by oleg-nenashev** [comment]
FTR there is a discussion in https://groups.google.com/forum/#!topic/jenkinsci-dev/c1z4C3mQ2-k about the future of the plugin

**Comment by darxriggs** [comment]
@oleg-nenashev thanks for the hint. @ikedam created the mentioned discussion due to all my pull requests here.

**Pull request merged**
